spring:
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/pet?useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=CTT
        hikari:
            minimum-idle: 10
            maximum-pool-size: 20
            idle-timeout: 500000
            max-lifetime: 500000
            connection-timeout: 60000
            connection-test-query: SELECT 1
server:
    port: 8087
